server:
  port: 8080
spring:
  application:
    #应用名称
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
  mail:
    host: smtp.qq.com
    username: 729765221@qq.com
    password: djioszgpoccibfgb
    default-encoding: UTF-8

  #邮箱配置
#  mail:
#    host: smtp.qq.com # 发送邮件的服务器地址
#    username: 729765221@qq.com # 开启 IMAP/SMTP服务 的qq邮箱的账号
#    password: ahobljrhtwjpbdfj # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
#    default-encoding: UTF-8

mybatis-plus:
  configuration:
    #address_book->AddressBook
    #在映射实体或属性时，将数据库中的表名和字段名中的下划线去掉，安装驼峰命名法映射
    map-underscore-to-camel-case: true
    #控制台打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #自动生成id类型为雪花算法
      id-type: ASSIGN_ID

#图片存储路径
reggie:
  path: D:\img\